package conversordedivisas;

import javax.swing.*;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Angel Cruz
 */
public class FrmConvert extends javax.swing.JFrame {
    //Objetos
    private CurrencyConvert convert;
    private Currency usd;
    private Currency mxn;
    private Currency eur;
    private Currency yen;
    
    void mostrarTable(){
        deMoneda.addItem("MXN");
        deMoneda.addItem("USA");
        deMoneda.addItem("EUR");
        deMoneda.addItem("YEN");
    }

    /**
     * Creates new form FrmConvert
     */
    public FrmConvert() {
        //Inizializar monedas disponibles
        usd = new Currency("USD", "$", "United States");
        eur = new Currency("EUR","€", "Eurozone" );
        mxn = new Currency("MXN", "$", "Mexico");
        yen = new Currency("YEN", "¥", "Japan");
        
        convert = new CurrencyConvert(20.65, 21.50, 0.96, 8);
        
        initComponents();
        this.setTitle("Conversor de divisas");
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/mxn.png"));
        this.setIconImage(icon); 
        iconMXN.setVisible(true);
        iconUSA.setVisible(false);
        iconEUR.setVisible(false);
        iconYEN.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtImporte = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        deMoneda = new javax.swing.JComboBox<>();
        aMoneda = new javax.swing.JComboBox<>();
        txtDe = new javax.swing.JLabel();
        txtA = new javax.swing.JLabel();
        iconUSA = new javax.swing.JLabel();
        iconMXN = new javax.swing.JLabel();
        iconEUR = new javax.swing.JLabel();
        iconYEN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtImporte.setText("Importe:");
        txtImporte.setOpaque(true);
        getContentPane().add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 35, -1, -1));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 57, 330, -1));

        btnConvertir.setBackground(new java.awt.Color(102, 102, 255));
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setText("Convertir");
        btnConvertir.setBorder(null);
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 90, 30));

        deMoneda.setForeground(new java.awt.Color(153, 255, 153));
        deMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MXN / Pesos Mexicanos", "EUR / Zona Europea", "USD / Estados Unidos", "YEN / Yen japones" }));
        deMoneda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deMonedaItemStateChanged(evt);
            }
        });
        deMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deMonedaActionPerformed(evt);
            }
        });
        getContentPane().add(deMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 107, 270, 50));

        aMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MXN / Peso Mexicano", "EUR / Zona Europea", "USD / Estados Unidos", "YEN / Yen Japones" }));
        aMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMonedaActionPerformed(evt);
            }
        });
        getContentPane().add(aMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 184, 270, 50));

        txtDe.setText("De:");
        getContentPane().add(txtDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 85, -1, -1));

        txtA.setText("A: ");
        getContentPane().add(txtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 163, -1, -1));

        iconUSA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usa.png"))); // NOI18N
        getContentPane().add(iconUSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 50));

        iconMXN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mxn.png"))); // NOI18N
        getContentPane().add(iconMXN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        iconEUR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eur.png"))); // NOI18N
        getContentPane().add(iconEUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 50));

        iconYEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/japon.png"))); // NOI18N
        getContentPane().add(iconYEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void deMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deMonedaActionPerformed

    private void aMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aMonedaActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        String amountTxt =  txtCantidad.getText();
        double amount = 0;
        
        try {
            amount = Double.parseDouble(amountTxt);
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa una cantidad válida","Error", JOptionPane.ERROR_MESSAGE);
            txtCantidad.setText("");
            return;
        } 
        
        //Obtener divisas seleccionadas
        String divisaOrigin  = (String) deMoneda.getSelectedItem();
        String divisaDestino = (String) aMoneda.getSelectedItem();
        
        String abrevOrigin = getAbreviatura(divisaOrigin);
        String abrevDestino = getAbreviatura(divisaDestino);
        
        double resultado = 0; 
        
        String conversionKey = abrevOrigin + "_" + abrevDestino;
        
        switch(conversionKey) {
            case "MXN_USD":
                resultado = convert.mxnToUsd(amount);
                break;
            case "MXN_EUR":
                resultado = convert.mxnToEur(amount);
                break;
            case "USD_MXN":
                resultado = convert.usdToMxn(amount);
                break;
            case "EUR_MXN":
                resultado = convert.eurToMxn(amount);
                break;
            case "EUR_USD":
                resultado = convert.eurToUsd(amount);
                break;
            case "USD_EUR":
                resultado = convert.usdToEur(amount);
                break;
            case "MXN_YEN":
                resultado = convert.mxnToYen(amount);
                break;
            case "YEN_MXN": 
                resultado = convert.yenToMxn(amount);
                break;
            default: 
                JOptionPane.showMessageDialog(this,"No soportamos este tipo de conversión", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
        }        
        txtCantidad.setText("");
        JOptionPane.showMessageDialog(this, String.format("Resultado: %.2f %s", resultado, abrevDestino), "Conversión exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnConvertirActionPerformed

    private String getAbreviatura(String divisa) {
        return divisa.split(" / ")[0].trim();
    }
    
    private void deMonedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deMonedaItemStateChanged
       
    String divisaOrigin  = (String) deMoneda.getSelectedItem();
    String divisaDestino = (String) aMoneda.getSelectedItem();
    
    String abrevOrigin = getAbreviatura(divisaOrigin);
    String abrevDestino = getAbreviatura(divisaDestino);
   
    // Comprueba si ambas abreviaturas coinciden
    if(abrevOrigin.equals("MXN")) {
        iconMXN.setVisible(true);  
        iconUSA.setVisible(false);
        iconEUR.setVisible(false);
    } else if (abrevOrigin.equals("USD")) {
        iconUSA.setVisible(true); 
        iconMXN.setVisible(false);
        iconEUR.setVisible(false);
    } else if (abrevOrigin.equals("EUR"))
        iconEUR.setVisible(true);
        iconUSA.setVisible(false); 
        iconMXN.setVisible(false);
    }//GEN-LAST:event_deMonedaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aMoneda;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> deMoneda;
    private javax.swing.JLabel iconEUR;
    private javax.swing.JLabel iconMXN;
    private javax.swing.JLabel iconUSA;
    private javax.swing.JLabel iconYEN;
    private javax.swing.JLabel txtA;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JLabel txtDe;
    private javax.swing.JLabel txtImporte;
    // End of variables declaration//GEN-END:variables
}
