package conversordedivisas;

import javax.swing.*;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author Angel Cruz
 */
public class FrmConvert extends javax.swing.JFrame {
    //Objetos
    private CurrencyConvert convert;
    private Currency usd;
    private Currency mxn;
    private Currency eur;

    /**
     * Creates new form FrmConvert
     */
    public FrmConvert() {
        usd = new Currency("USD", "$", "United States");
        eur = new Currency("EUR","€", "Eurozone" );
        mxn = new Currency("MXN", "$", "Mexico");
        
        
        convert = new CurrencyConvert(20.65, 21.50, 0.96);
        
        initComponents();
        this.setTitle("Conversor de divisas");
        this.setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/mxn.png"));
        this.setIconImage(icon); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtImporte = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        deMoneda = new javax.swing.JComboBox<>();
        aMoneda = new javax.swing.JComboBox<>();
        txtDe = new javax.swing.JLabel();
        txtA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        txtImporte.setText("Importe");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnConvertir.setBackground(new java.awt.Color(102, 102, 255));
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        deMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MXN / Peso Mexicano", "EUR / Zona Europea", "USD / Estados Unidos" }));
        deMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deMonedaActionPerformed(evt);
            }
        });

        aMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MXN / Peso Mexicano", "EUR / Zona Europea", "USD / Estados Unidos" }));
        aMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMonedaActionPerformed(evt);
            }
        });

        txtDe.setText("De:");

        txtA.setText("A: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtA)
                            .addComponent(txtDe)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtImporte)
                                .addComponent(txtCantidad)
                                .addComponent(deMoneda, 0, 280, Short.MAX_VALUE)
                                .addComponent(aMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnConvertir)
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(txtImporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(txtDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtA)
                .addGap(5, 5, 5)
                .addComponent(aMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnConvertir)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void deMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deMonedaActionPerformed

    private void aMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aMonedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aMonedaActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        String amountTxt =  txtCantidad.getText();
        double amount = 0;
        
        try {
            amount = Double.parseDouble(amountTxt);
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingresa una cantidad válida");
            return;
        } 
        
        //Obtener divisas seleccionadas
        String divisaOrigin  = (String) deMoneda.getSelectedItem();
        String divisaDestino = (String) aMoneda.getSelectedItem();
        
        String abrevOrigin = divisaOrigin.split(" / ")[0].trim();
        String abrevDestino = divisaDestino.split(" / ")[0].trim();
        
        double resultado = 0; 
        
        String conversionKey = abrevOrigin + "_" + abrevDestino;
        
        switch(conversionKey) {
            case "MXN_USD":
                resultado = convert.mxnToUsd(amount);
                break;
            case "MXN_EUR":
                resultado = convert.eurToMxn(amount);
                break;
            case "USD_MXN":
                resultado = convert.usdToMxn(amount);
                break;
            case "EUR_MXN":
                resultado = convert.usdToEur(amount);
                break;
            case "EUR_USD":
                resultado = convert.eurToUsd(amount);
                break;
            case "USD_EUR":
                resultado = convert.usdToEur(amount);
                break;
            default: 
                JOptionPane.showMessageDialog(this,"No soportamos este tipo de conversión", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
        }        
        txtCantidad.setText("");
        JOptionPane.showMessageDialog(this, String.format("Resultado: %.2f %s", resultado, abrevDestino), "Conversión exitosa", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aMoneda;
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> deMoneda;
    private javax.swing.JLabel txtA;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JLabel txtDe;
    private javax.swing.JLabel txtImporte;
    // End of variables declaration//GEN-END:variables
}
