package forms;

import java.util.List;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import volumenes.Volumenes;

public class VolumenesForm extends javax.swing.JFrame {
  private final Volumenes v;

  public VolumenesForm() {
    v = new Volumenes();
    initComponents();
    setTitle("Calcular volumenes");

    cubo.setVisible(true);
    cilindro.setVisible(false);
    esfera.setVisible(false);

    txtLado.setVisible(true);
    txtAltura.setVisible(false);
    txtRadio.setVisible(false);

    labelLado.setVisible(true);
    labelAltura.setVisible(false);
    labelRadio.setVisible(false);

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    cubo = new javax.swing.JLabel();
    cilindro = new javax.swing.JLabel();
    esfera = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    cbmFiguras = new javax.swing.JComboBox<>();
    jLabel5 = new javax.swing.JLabel();
    labelLado = new javax.swing.JLabel();
    txtLado = new javax.swing.JTextField();
    btnCalcular = new javax.swing.JButton();
    txtRadio = new javax.swing.JTextField();
    txtAltura = new javax.swing.JTextField();
    labelRadio = new javax.swing.JLabel();
    labelAltura = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    cubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cubo.png"))); // NOI18N
    getContentPane().add(cubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

    cilindro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cilindro.png"))); // NOI18N
    getContentPane().add(cilindro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

    esfera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/esfera.png"))); // NOI18N
    getContentPane().add(esfera, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

    jLabel4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
    jLabel4.setText("Cálculo de volumenes");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

    cbmFiguras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cubo", "Esfera", "Cilindro", " " }));
    cbmFiguras.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cbmFigurasItemStateChanged(evt);
      }
    });
    cbmFiguras.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbmFigurasActionPerformed(evt);
      }
    });
    getContentPane().add(cbmFiguras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 160, -1));

    jLabel5.setText("Selecciona la figura que quieres calcular el volumen:");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

    labelLado.setText("Ingrese la medida del lado:");
    getContentPane().add(labelLado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
    getContentPane().add(txtLado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 140, -1));

    btnCalcular.setText("Calcular");
    btnCalcular.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCalcularActionPerformed(evt);
      }
    });
    getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

    txtRadio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtRadioActionPerformed(evt);
      }
    });
    getContentPane().add(txtRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 140, -1));
    getContentPane().add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 140, -1));

    labelRadio.setText("Ingrese el radio:");
    getContentPane().add(labelRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

    labelAltura.setText("Ingrese la altura:");
    getContentPane().add(labelAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cbmFigurasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbmFigurasActionPerformed

  }// GEN-LAST:event_cbmFigurasActionPerformed

  private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCalcularActionPerformed
    String figuraSeleccionada = (String) cbmFiguras.getSelectedItem();

    switch (figuraSeleccionada) {
      case "Cubo" -> {
        double lado = Double.parseDouble(txtLado.getText());
        v.volumenCubo(lado);
      }
      case "Esfera" -> {
        double radio = Double.parseDouble(txtRadio.getText());
        v.volumenEsfera(radio);
      }
      case "Cilindro" -> {
        double radio = Double.parseDouble(txtRadio.getText());
        double altura = Double.parseDouble(txtAltura.getText());
        v.volumenCilindro(radio, altura);
      }
      default -> {
      }
    }

    JOptionPane.showMessageDialog(this, "El volumen es: " + String.format("%.3f", v.getVolumen()) + " cm³");

  }// GEN-LAST:event_btnCalcularActionPerformed

  private void toggleInputs(List<JLabel> icons, List<JTextField> inputs, List<JLabel> messages) {
    icons.forEach(icon -> icon.setVisible(false));
    inputs.forEach(input -> input.setVisible(false));
    messages.forEach(message -> message.setVisible(false));
  }

  private void cbmFigurasItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbmFigurasItemStateChanged
    String figuraSeleccionada = (String) cbmFiguras.getSelectedItem();

    List<JLabel> icons = List.of(cubo, cilindro, cilindro);
    List<JTextField> inputs = List.of(txtLado, txtRadio, txtAltura);
    List<JLabel> messages = List.of(labelLado, labelAltura, labelRadio);

    toggleInputs(icons, inputs, messages);

    switch (figuraSeleccionada) {
      case "Cubo" -> {
        cubo.setVisible(true);
        labelLado.setVisible(true);
        txtLado.setVisible(true);
      }
      case "Cilindro" -> {
        cilindro.setVisible(true);
        txtRadio.setVisible(true);
        labelRadio.setVisible(true);
        txtAltura.setVisible(true);
        labelAltura.setVisible(true);
      }
      case "Esfera" -> {
        esfera.setVisible(true);
        txtRadio.setVisible(true);
        labelRadio.setVisible(true);
      }
      default -> {
      }
    }
  }// GEN-LAST:event_cbmFigurasItemStateChanged

  private void txtRadioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtRadioActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txtRadioActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VolumenesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VolumenesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VolumenesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VolumenesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    // </editor-fold>
    // </editor-fold>
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VolumenesForm().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCalcular;
  private javax.swing.JComboBox<String> cbmFiguras;
  private javax.swing.JLabel cilindro;
  private javax.swing.JLabel cubo;
  private javax.swing.JLabel esfera;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel labelAltura;
  private javax.swing.JLabel labelLado;
  private javax.swing.JLabel labelRadio;
  private javax.swing.JTextField txtAltura;
  private javax.swing.JTextField txtLado;
  private javax.swing.JTextField txtRadio;
  // End of variables declaration//GEN-END:variables
}
